x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-db/${POSTGRES_DB}
    AIRFLOW__CELERY__BROKER_URL: redis://airflow-redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-db/${POSTGRES_DB}
    AIRFLOW__WEBSERVER__SECRET_KEY: 'project'
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcloud_key.json
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./scripts:/opt/airflow/scripts

services:
  airflow-db:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_net

  airflow-redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "6379:6379"
    networks:
      - airflow_net

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command: >
      -c "airflow db init && airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email beminiwa@gmail.com"
    depends_on:
      - airflow-db
      - airflow-redis
    networks:
      - airflow_net
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: ${AIRFLOW_WEBSERVER_CONTAINER_NAME}
    ports:
      - "${AIRFLOW_WEBSERVER_PORT}:8080"
    depends_on:
      - airflow-db
      - airflow-init
    command: webserver
    networks:
      - airflow_net

  airflow-scheduler:
    <<: *airflow-common
    container_name: ${AIRFLOW_SCHEDULER_CONTAINER_NAME}
    depends_on:
      - airflow-db
      - airflow-init
    command: scheduler
    networks:
      - airflow_net

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker
    depends_on:
      - airflow-db
      - airflow-redis
      - airflow-init
    networks:
      - airflow_net
    deploy:
      resources:
        limits:
          cpus: "2.5"
          memory: 4G

volumes:
  postgres_data:

networks:
  airflow_net:
    driver: bridge

